version: '3'
services:
  elasticnode1: 
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    mem_limit: ${MEM_LIMIT}
    ulimits: 
      memlock: 
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esnode1:/usr/share/elasticsearch/data
  kibana: 
    image: docker.elastic.co/kibana/kibana:8.8.1
    depends_on: 
       - elasticnode1
    environment: 
      - SERVERNAME=kibana 
      - ELASTICSEARCH_HOSTS=http://elasticnode1:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    volumes: 
      - kibanadata:/usr/share/kibana/data
    ports: 
      - 5601:5601
    mem_limit: ${MEM_LIMIT}
volumes: 
  esnode1: 
    driver: local
  kibanadata: 
    driver: local
